weatherdata <- read.table('C:/Users/MCA-29/R Practical/daily-min-temperatures.csv', sep=",", header= TRUE)
head(weatherdata)
plot.ts(weatherdata$Temp, main="Weather", ylab="Temperature")
plot.ts(log(weatherdata$Temp),main="Weather", ylab="Temperature")
temperature.timeseries <- ts(weatherdata$Temp)
plot.ts(temperature.timeseries)
datats=ts(weatherdata,start = c(2012,1),frequency = 12)
plot(decompose(datats))
msft_ar <- arima(temperature.timeseries, order = c(1, 2, 2))
print(msft_ar)